version: '3.8'

services:
  frontend:
    image: ${DOCKER_USERNAME}/todo-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - backend
    environment:
      - VUE_APP_API_URL=http://localhost:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    image: ${DOCKER_USERNAME}/todo-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_PORT=5432
    volumes:
      - ./backend:/app
      - /app/node_modules

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: 